### ISSUE TITLE
Unity 2019.4.29f1 (VRChat) changes some UnityEngine and UnityEditor features from Experimental 

### ISSUE THREAD

**Issue by Lhun** [momoma-null/MomomaTools#2]
Unity 2019 has graduated some features from Experimental to included, so I've replaced those references in the header. 
I have made a proper pull request with my changes with your changes from a few hours ago. 
It seems to allow merging without any trouble, but you will know for sure. 
https://github.com/momoma-null/MomomaTools/pull/1

**Comment by momoma-null** [comment]
I have already deleted old scripts.
See also https://github.com/momoma-null/MomomaAssetProcessor
