### ISSUE TITLE
VRC_SDK_WORLD is no longer supported

### ISSUE THREAD

**Issue by esnya** [momoma-null/MomomaTools#3]
`VRC_SDK_WORLD` is not defined in the new SDKs. Therefore, these lines will result in an error. I replaced them with `UDON` and they worked.

https://github.com/momoma-null/MomomaTools/blob/3fb46a927f433c03247b8fd8669a5ff4249b6af9/Editor/AnimatorControllerMixer.cs#L7
https://github.com/momoma-null/MomomaTools/blob/3fb46a927f433c03247b8fd8669a5ff4249b6af9/Editor/AnimatorControllerMixer.cs#L309
https://github.com/momoma-null/MomomaTools/blob/3fb46a927f433c03247b8fd8669a5ff4249b6af9/Editor/AnimatorControllerMixer.cs#L330

**Comment by momoma-null** [comment]
`VRC_SDK_WORLD` is defined in MomomaAssets.Editor.asmdef, so there must be no problem.
But I think using `UDON` is better, thank you.
